### PR TITLE
Add ability to use models from private repositories

### PR DESCRIPTION
**Pull request by davidcoallier**
## Introduction 🤞

Big fan of HappyTransformer, but I've noticed that we're lacking the ability to use private repositories. This pull-request implements the `use_auth_token` which we use in our fork. 

I was considering simply adding a reference to `**kwargs` and pass that to the `from_pretrained(...)` calls but decided against it. 

## Documentation 📘

Every model's documentation has been updated to reflect the new API capability. 

## Backwards Compatibility 👀

The does not break API backwards compatibility 🙏

## Further Discussions 💬

One thing I've noticed missing from HF is using an environment variable to pass the auth token instead of having it explicitly defined as part of the model calls. 

This is something I'd like to explore and figure out if it's any interest to you. If so I'll take a stab. 🤷‍♂️

### CODE REVIEW

**Review by EricFillion — APPROVED** [review]
Fantastic work! Nice job with updating the documentation too. I'm looking forward to using this new feature.

**Comment by EricFillion** [comment]
Version 2.3.2 is live and contains these changes! Thanks for your help.

**Comment by davidcoallier** [comment]
Great thanks!

**Comment by davidcoallier** [comment]
Just noticed something isn't working right. Must have missed something when porting-back. Investigating now. Might be worth reverting unless I find a fix this morning on the train.

**Comment by davidcoallier** [comment]
Ok I found the problem, will issue a new PR to address it. Somehow forgot to include the __init__ use_auth_token when porting the code over.

**Pull request merged**
