### PR TITLE
QA Training And New Architecture

### PR DESCRIPTION
**Pull request by EricFillion**
Added new methods for question answering: 
- Training  ".train()"
- Evaluating  " .eval()"
- Testing  ".test()"

Implemented the new architecture for QA, in full. 

Implemented the new architecture for MWP, in skeleton code 

Moved everything that's not relevant to the new architecture to a folder called "to_delete"

Please ignore the changes to the files under the to_delete folder.

### CODE REVIEW

**Comment by ted537** [comment]
There's a lot going on here. Could you delete the "to_delete" folder and remove / update any tests that depend on stuff in there?

**Comment by ted537** [comment]
What's with the empty `__init__.py` files in subfolders?

**Comment by EricFillion** [comment]
@ted537 

I deleted files that do not follow the new architecture. I also deleted __init__.py files, that are likely not required for the final release. Finally, I modified the __init__.py under the happytransformer  folder, which I know to be required.

**Comment by ted537** [comment]
```
happytasks/
├── happy_mwp
│   ├── default_args_mwp.py
│   └── trainer_mwp.py
├── happy_qa
│   ├── default_args_qa.py
│   ├── qa_util.py
│   └── trainer_qa.py
```

These appear to be pretty noisy names. I feel like this would be equally descriptive and more concise.

```
happytransformer/
├── mwp
└── qa
└── ... etcetera
```

**Comment by EricFillion** [comment]
> ```
> happytasks/
> ├── happy_mwp
> │   ├── default_args_mwp.py
> │   └── trainer_mwp.py
> ├── happy_qa
> │   ├── default_args_qa.py
> │   ├── qa_util.py
> │   └── trainer_qa.py
> ```
> 
> These appear to be pretty noisy names. I feel like this would be equally descriptive and more concise.
> 
> ```
> happytransformer/
> ├── mwp
> └── qa
> └── ... etcetera
> ```

I kept the HappyQuestionAnswering and HappyWordPrediction directly under the HappyTransformer folder so that they can be directly imported "from happytransformer import happywordprediction" rather than "from happytansformer.mwp import happywordprediction"

I'm open to changing the names under the happytasks folder to make it more clear.

**Comment by ted537** [comment]
```
from happytransformer.happytasks.happy_mwp.trainer_mwp import something
```
This sparks the following questions:
- Why is MWP listed multiple times?
- What does happytasks mean? What would and wouldn't be under it?
- Why is happy listed multiple times?
 
The following would not spark these questions
```
from happytransformer.mwp.trainer import something
```

Note that these concerns do not face the end user but they're nonetheless important for our internal sanity

**Comment by EricFillion** [comment]
**Why is MWP listed multiple times?**

I suppose we can remove the "_mwp" from "trainer_mwp", just comes down to styling. 

**What does happytasks mean? What would and wouldn't be under it?**

A happytask is a name for child class of HappyTransformer objects, like HappyWordPrediction. In this case, the task is "WordPrediction." So, happy + task = "Happy" + "WordPrediction" = "HappyWordPrediction" 

I created the folder to separate most of the the non user-facing code  

**Why is happy listed multiple times?** 
Again, just styling. 

I'll go ahead and change it to follow the format you're proposing.

**Comment by ted537** [comment]
Could you add some tests for the new architecture? These would double as concrete examples

**Comment by EricFillion** [comment]
> Could you add some tests for the new architecture? These would double as concrete examples

I modified the old QA tests to follow the new architecture, found under test_qa_multi.py and test_task_util.py. I left the other old tests as well, although of course they do not work as we have to re add functionality for MWP, NSP and TC. But after we add the functionality, it should only involve modifying a few lines of code to get them working again. 

I also included tests for testing the question answering training functionality under "test_qa_trainer.py"

**Comment by ted537** [comment]
The following tests are now outdated:

- `test_next_sentence_probs.py`
- `test_multi_mask.py`
- `test_next_sentence_prediction.py`
- `test_predict.py`
- `test_sequence.py`

**Pull request merged**
